spring.application.name=platform
spring.datasource.url=jdbc:postgresql://localhost:5432/Enterprise_Ai_platform
spring.datasource.username=postgres
spring.datasource.password=Jaiv9164
spring.jpa.hibernate.ddl-auto=update

jwt.secret="ddgdbydjsmsjjsmhdgdndjsksjbdddjdkddk"
server.port=8081